/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosDeGuinchoEReboqueRouteImport } from './routes/servicos-de-guincho-e-reboque'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RodoviasValeDoParaibaRouteImport } from './routes/rodovias-vale-do-paraiba'
import { Route as RemocaoVeicularRouteImport } from './routes/remocao-veicular'
import { Route as PaneSecaRouteImport } from './routes/pane-seca'
import { Route as GuinchosNasRodoviasChar123slugChar125RouteImport } from './routes/guinchos-nas-rodovias-{$slug}'
import { Route as GuinchoChar123tipoChar125SjcRouteImport } from './routes/guincho-{$tipo}-sjc'
import { Route as GuinchoPostosDutraSaoJoseDosCamposRouteImport } from './routes/guincho-postos-dutra-sao-jose-dos-campos'
import { Route as GuinchoPesadoRouteImport } from './routes/guincho-pesado'
import { Route as GuinchoLeveRouteImport } from './routes/guincho-leve'
import { Route as GuinchoEmChar123slugChar125RouteImport } from './routes/guincho-em-{$slug}'
import { Route as GuinchoDeMotosRouteImport } from './routes/guincho-de-motos'
import { Route as FrotaGuinchoRouteImport } from './routes/frota-guincho'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AutoSocorroRouteImport } from './routes/auto-socorro'
import { Route as AreasAtendidasRouteImport } from './routes/areas-atendidas'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuinchoChar123tipoChar125SjcIndexRouteImport } from './routes/guincho-{$tipo}-sjc.index'
import { Route as GuinchoSjcIndexRouteImport } from './routes/guincho-sjc.index'
import { Route as GuinchoChar123tipoChar125SjcBairroRouteImport } from './routes/guincho-{$tipo}-sjc.$bairro'
import { Route as GuinchoSjcBairroRouteImport } from './routes/guincho-sjc.$bairro'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ServicosDeGuinchoEReboqueRoute =
  ServicosDeGuinchoEReboqueRouteImport.update({
    id: '/servicos-de-guincho-e-reboque',
    path: '/servicos-de-guincho-e-reboque',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RodoviasValeDoParaibaRoute = RodoviasValeDoParaibaRouteImport.update({
  id: '/rodovias-vale-do-paraiba',
  path: '/rodovias-vale-do-paraiba',
  getParentRoute: () => rootRouteImport,
} as any)
const RemocaoVeicularRoute = RemocaoVeicularRouteImport.update({
  id: '/remocao-veicular',
  path: '/remocao-veicular',
  getParentRoute: () => rootRouteImport,
} as any)
const PaneSecaRoute = PaneSecaRouteImport.update({
  id: '/pane-seca',
  path: '/pane-seca',
  getParentRoute: () => rootRouteImport,
} as any)
const GuinchosNasRodoviasChar123slugChar125Route =
  GuinchosNasRodoviasChar123slugChar125RouteImport.update({
    id: '/guinchos-nas-rodovias-{$slug}',
    path: '/guinchos-nas-rodovias-{$slug}',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuinchoChar123tipoChar125SjcRoute =
  GuinchoChar123tipoChar125SjcRouteImport.update({
    id: '/guincho-{$tipo}-sjc',
    path: '/guincho-{$tipo}-sjc',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuinchoPostosDutraSaoJoseDosCamposRoute =
  GuinchoPostosDutraSaoJoseDosCamposRouteImport.update({
    id: '/guincho-postos-dutra-sao-jose-dos-campos',
    path: '/guincho-postos-dutra-sao-jose-dos-campos',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuinchoPesadoRoute = GuinchoPesadoRouteImport.update({
  id: '/guincho-pesado',
  path: '/guincho-pesado',
  getParentRoute: () => rootRouteImport,
} as any)
const GuinchoLeveRoute = GuinchoLeveRouteImport.update({
  id: '/guincho-leve',
  path: '/guincho-leve',
  getParentRoute: () => rootRouteImport,
} as any)
const GuinchoEmChar123slugChar125Route =
  GuinchoEmChar123slugChar125RouteImport.update({
    id: '/guincho-em-{$slug}',
    path: '/guincho-em-{$slug}',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuinchoDeMotosRoute = GuinchoDeMotosRouteImport.update({
  id: '/guincho-de-motos',
  path: '/guincho-de-motos',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaGuinchoRoute = FrotaGuinchoRouteImport.update({
  id: '/frota-guincho',
  path: '/frota-guincho',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoSocorroRoute = AutoSocorroRouteImport.update({
  id: '/auto-socorro',
  path: '/auto-socorro',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAtendidasRoute = AreasAtendidasRouteImport.update({
  id: '/areas-atendidas',
  path: '/areas-atendidas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuinchoChar123tipoChar125SjcIndexRoute =
  GuinchoChar123tipoChar125SjcIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GuinchoChar123tipoChar125SjcRoute,
  } as any)
const GuinchoSjcIndexRoute = GuinchoSjcIndexRouteImport.update({
  id: '/guincho-sjc/',
  path: '/guincho-sjc/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuinchoChar123tipoChar125SjcBairroRoute =
  GuinchoChar123tipoChar125SjcBairroRouteImport.update({
    id: '/$bairro',
    path: '/$bairro',
    getParentRoute: () => GuinchoChar123tipoChar125SjcRoute,
  } as any)
const GuinchoSjcBairroRoute = GuinchoSjcBairroRouteImport.update({
  id: '/guincho-sjc/$bairro',
  path: '/guincho-sjc/$bairro',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/areas-atendidas': typeof AreasAtendidasRoute
  '/auto-socorro': typeof AutoSocorroRoute
  '/blog': typeof BlogRouteWithChildren
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/frota-guincho': typeof FrotaGuinchoRoute
  '/guincho-de-motos': typeof GuinchoDeMotosRoute
  '/guincho-em-{$slug}': typeof GuinchoEmChar123slugChar125Route
  '/guincho-leve': typeof GuinchoLeveRoute
  '/guincho-pesado': typeof GuinchoPesadoRoute
  '/guincho-postos-dutra-sao-jose-dos-campos': typeof GuinchoPostosDutraSaoJoseDosCamposRoute
  '/guincho-{$tipo}-sjc': typeof GuinchoChar123tipoChar125SjcRouteWithChildren
  '/guinchos-nas-rodovias-{$slug}': typeof GuinchosNasRodoviasChar123slugChar125Route
  '/pane-seca': typeof PaneSecaRoute
  '/remocao-veicular': typeof RemocaoVeicularRoute
  '/rodovias-vale-do-paraiba': typeof RodoviasValeDoParaibaRoute
  '/servicos': typeof ServicosRoute
  '/servicos-de-guincho-e-reboque': typeof ServicosDeGuinchoEReboqueRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guincho-sjc/$bairro': typeof GuinchoSjcBairroRoute
  '/guincho-{$tipo}-sjc/$bairro': typeof GuinchoChar123tipoChar125SjcBairroRoute
  '/guincho-sjc/': typeof GuinchoSjcIndexRoute
  '/guincho-{$tipo}-sjc/': typeof GuinchoChar123tipoChar125SjcIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/areas-atendidas': typeof AreasAtendidasRoute
  '/auto-socorro': typeof AutoSocorroRoute
  '/blog': typeof BlogRouteWithChildren
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/frota-guincho': typeof FrotaGuinchoRoute
  '/guincho-de-motos': typeof GuinchoDeMotosRoute
  '/guincho-em-{$slug}': typeof GuinchoEmChar123slugChar125Route
  '/guincho-leve': typeof GuinchoLeveRoute
  '/guincho-pesado': typeof GuinchoPesadoRoute
  '/guincho-postos-dutra-sao-jose-dos-campos': typeof GuinchoPostosDutraSaoJoseDosCamposRoute
  '/guinchos-nas-rodovias-{$slug}': typeof GuinchosNasRodoviasChar123slugChar125Route
  '/pane-seca': typeof PaneSecaRoute
  '/remocao-veicular': typeof RemocaoVeicularRoute
  '/rodovias-vale-do-paraiba': typeof RodoviasValeDoParaibaRoute
  '/servicos': typeof ServicosRoute
  '/servicos-de-guincho-e-reboque': typeof ServicosDeGuinchoEReboqueRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guincho-sjc/$bairro': typeof GuinchoSjcBairroRoute
  '/guincho-{$tipo}-sjc/$bairro': typeof GuinchoChar123tipoChar125SjcBairroRoute
  '/guincho-sjc': typeof GuinchoSjcIndexRoute
  '/guincho-{$tipo}-sjc': typeof GuinchoChar123tipoChar125SjcIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/areas-atendidas': typeof AreasAtendidasRoute
  '/auto-socorro': typeof AutoSocorroRoute
  '/blog': typeof BlogRouteWithChildren
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/frota-guincho': typeof FrotaGuinchoRoute
  '/guincho-de-motos': typeof GuinchoDeMotosRoute
  '/guincho-em-{$slug}': typeof GuinchoEmChar123slugChar125Route
  '/guincho-leve': typeof GuinchoLeveRoute
  '/guincho-pesado': typeof GuinchoPesadoRoute
  '/guincho-postos-dutra-sao-jose-dos-campos': typeof GuinchoPostosDutraSaoJoseDosCamposRoute
  '/guincho-{$tipo}-sjc': typeof GuinchoChar123tipoChar125SjcRouteWithChildren
  '/guinchos-nas-rodovias-{$slug}': typeof GuinchosNasRodoviasChar123slugChar125Route
  '/pane-seca': typeof PaneSecaRoute
  '/remocao-veicular': typeof RemocaoVeicularRoute
  '/rodovias-vale-do-paraiba': typeof RodoviasValeDoParaibaRoute
  '/servicos': typeof ServicosRoute
  '/servicos-de-guincho-e-reboque': typeof ServicosDeGuinchoEReboqueRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guincho-sjc/$bairro': typeof GuinchoSjcBairroRoute
  '/guincho-{$tipo}-sjc/$bairro': typeof GuinchoChar123tipoChar125SjcBairroRoute
  '/guincho-sjc/': typeof GuinchoSjcIndexRoute
  '/guincho-{$tipo}-sjc/': typeof GuinchoChar123tipoChar125SjcIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anuncie'
    | '/areas-atendidas'
    | '/auto-socorro'
    | '/blog'
    | '/cobertura'
    | '/contato'
    | '/frota-guincho'
    | '/guincho-de-motos'
    | '/guincho-em-{$slug}'
    | '/guincho-leve'
    | '/guincho-pesado'
    | '/guincho-postos-dutra-sao-jose-dos-campos'
    | '/guincho-{$tipo}-sjc'
    | '/guinchos-nas-rodovias-{$slug}'
    | '/pane-seca'
    | '/remocao-veicular'
    | '/rodovias-vale-do-paraiba'
    | '/servicos'
    | '/servicos-de-guincho-e-reboque'
    | '/blog/$slug'
    | '/guincho-sjc/$bairro'
    | '/guincho-{$tipo}-sjc/$bairro'
    | '/guincho-sjc/'
    | '/guincho-{$tipo}-sjc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anuncie'
    | '/areas-atendidas'
    | '/auto-socorro'
    | '/blog'
    | '/cobertura'
    | '/contato'
    | '/frota-guincho'
    | '/guincho-de-motos'
    | '/guincho-em-{$slug}'
    | '/guincho-leve'
    | '/guincho-pesado'
    | '/guincho-postos-dutra-sao-jose-dos-campos'
    | '/guinchos-nas-rodovias-{$slug}'
    | '/pane-seca'
    | '/remocao-veicular'
    | '/rodovias-vale-do-paraiba'
    | '/servicos'
    | '/servicos-de-guincho-e-reboque'
    | '/blog/$slug'
    | '/guincho-sjc/$bairro'
    | '/guincho-{$tipo}-sjc/$bairro'
    | '/guincho-sjc'
    | '/guincho-{$tipo}-sjc'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anuncie'
    | '/areas-atendidas'
    | '/auto-socorro'
    | '/blog'
    | '/cobertura'
    | '/contato'
    | '/frota-guincho'
    | '/guincho-de-motos'
    | '/guincho-em-{$slug}'
    | '/guincho-leve'
    | '/guincho-pesado'
    | '/guincho-postos-dutra-sao-jose-dos-campos'
    | '/guincho-{$tipo}-sjc'
    | '/guinchos-nas-rodovias-{$slug}'
    | '/pane-seca'
    | '/remocao-veicular'
    | '/rodovias-vale-do-paraiba'
    | '/servicos'
    | '/servicos-de-guincho-e-reboque'
    | '/blog/$slug'
    | '/guincho-sjc/$bairro'
    | '/guincho-{$tipo}-sjc/$bairro'
    | '/guincho-sjc/'
    | '/guincho-{$tipo}-sjc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnuncieRoute: typeof AnuncieRoute
  AreasAtendidasRoute: typeof AreasAtendidasRoute
  AutoSocorroRoute: typeof AutoSocorroRoute
  BlogRoute: typeof BlogRouteWithChildren
  CoberturaRoute: typeof CoberturaRoute
  ContatoRoute: typeof ContatoRoute
  FrotaGuinchoRoute: typeof FrotaGuinchoRoute
  GuinchoDeMotosRoute: typeof GuinchoDeMotosRoute
  GuinchoEmChar123slugChar125Route: typeof GuinchoEmChar123slugChar125Route
  GuinchoLeveRoute: typeof GuinchoLeveRoute
  GuinchoPesadoRoute: typeof GuinchoPesadoRoute
  GuinchoPostosDutraSaoJoseDosCamposRoute: typeof GuinchoPostosDutraSaoJoseDosCamposRoute
  GuinchoChar123tipoChar125SjcRoute: typeof GuinchoChar123tipoChar125SjcRouteWithChildren
  GuinchosNasRodoviasChar123slugChar125Route: typeof GuinchosNasRodoviasChar123slugChar125Route
  PaneSecaRoute: typeof PaneSecaRoute
  RemocaoVeicularRoute: typeof RemocaoVeicularRoute
  RodoviasValeDoParaibaRoute: typeof RodoviasValeDoParaibaRoute
  ServicosRoute: typeof ServicosRoute
  ServicosDeGuinchoEReboqueRoute: typeof ServicosDeGuinchoEReboqueRoute
  GuinchoSjcBairroRoute: typeof GuinchoSjcBairroRoute
  GuinchoSjcIndexRoute: typeof GuinchoSjcIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos-de-guincho-e-reboque': {
      id: '/servicos-de-guincho-e-reboque'
      path: '/servicos-de-guincho-e-reboque'
      fullPath: '/servicos-de-guincho-e-reboque'
      preLoaderRoute: typeof ServicosDeGuinchoEReboqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rodovias-vale-do-paraiba': {
      id: '/rodovias-vale-do-paraiba'
      path: '/rodovias-vale-do-paraiba'
      fullPath: '/rodovias-vale-do-paraiba'
      preLoaderRoute: typeof RodoviasValeDoParaibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remocao-veicular': {
      id: '/remocao-veicular'
      path: '/remocao-veicular'
      fullPath: '/remocao-veicular'
      preLoaderRoute: typeof RemocaoVeicularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pane-seca': {
      id: '/pane-seca'
      path: '/pane-seca'
      fullPath: '/pane-seca'
      preLoaderRoute: typeof PaneSecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guinchos-nas-rodovias-{$slug}': {
      id: '/guinchos-nas-rodovias-{$slug}'
      path: '/guinchos-nas-rodovias-{$slug}'
      fullPath: '/guinchos-nas-rodovias-{$slug}'
      preLoaderRoute: typeof GuinchosNasRodoviasChar123slugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-{$tipo}-sjc': {
      id: '/guincho-{$tipo}-sjc'
      path: '/guincho-{$tipo}-sjc'
      fullPath: '/guincho-{$tipo}-sjc'
      preLoaderRoute: typeof GuinchoChar123tipoChar125SjcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-postos-dutra-sao-jose-dos-campos': {
      id: '/guincho-postos-dutra-sao-jose-dos-campos'
      path: '/guincho-postos-dutra-sao-jose-dos-campos'
      fullPath: '/guincho-postos-dutra-sao-jose-dos-campos'
      preLoaderRoute: typeof GuinchoPostosDutraSaoJoseDosCamposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-pesado': {
      id: '/guincho-pesado'
      path: '/guincho-pesado'
      fullPath: '/guincho-pesado'
      preLoaderRoute: typeof GuinchoPesadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-leve': {
      id: '/guincho-leve'
      path: '/guincho-leve'
      fullPath: '/guincho-leve'
      preLoaderRoute: typeof GuinchoLeveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-em-{$slug}': {
      id: '/guincho-em-{$slug}'
      path: '/guincho-em-{$slug}'
      fullPath: '/guincho-em-{$slug}'
      preLoaderRoute: typeof GuinchoEmChar123slugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-de-motos': {
      id: '/guincho-de-motos'
      path: '/guincho-de-motos'
      fullPath: '/guincho-de-motos'
      preLoaderRoute: typeof GuinchoDeMotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota-guincho': {
      id: '/frota-guincho'
      path: '/frota-guincho'
      fullPath: '/frota-guincho'
      preLoaderRoute: typeof FrotaGuinchoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-socorro': {
      id: '/auto-socorro'
      path: '/auto-socorro'
      fullPath: '/auto-socorro'
      preLoaderRoute: typeof AutoSocorroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-atendidas': {
      id: '/areas-atendidas'
      path: '/areas-atendidas'
      fullPath: '/areas-atendidas'
      preLoaderRoute: typeof AreasAtendidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-{$tipo}-sjc/': {
      id: '/guincho-{$tipo}-sjc/'
      path: '/'
      fullPath: '/guincho-{$tipo}-sjc/'
      preLoaderRoute: typeof GuinchoChar123tipoChar125SjcIndexRouteImport
      parentRoute: typeof GuinchoChar123tipoChar125SjcRoute
    }
    '/guincho-sjc/': {
      id: '/guincho-sjc/'
      path: '/guincho-sjc'
      fullPath: '/guincho-sjc/'
      preLoaderRoute: typeof GuinchoSjcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-{$tipo}-sjc/$bairro': {
      id: '/guincho-{$tipo}-sjc/$bairro'
      path: '/$bairro'
      fullPath: '/guincho-{$tipo}-sjc/$bairro'
      preLoaderRoute: typeof GuinchoChar123tipoChar125SjcBairroRouteImport
      parentRoute: typeof GuinchoChar123tipoChar125SjcRoute
    }
    '/guincho-sjc/$bairro': {
      id: '/guincho-sjc/$bairro'
      path: '/guincho-sjc/$bairro'
      fullPath: '/guincho-sjc/$bairro'
      preLoaderRoute: typeof GuinchoSjcBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface GuinchoChar123tipoChar125SjcRouteChildren {
  GuinchoChar123tipoChar125SjcBairroRoute: typeof GuinchoChar123tipoChar125SjcBairroRoute
  GuinchoChar123tipoChar125SjcIndexRoute: typeof GuinchoChar123tipoChar125SjcIndexRoute
}

const GuinchoChar123tipoChar125SjcRouteChildren: GuinchoChar123tipoChar125SjcRouteChildren =
  {
    GuinchoChar123tipoChar125SjcBairroRoute:
      GuinchoChar123tipoChar125SjcBairroRoute,
    GuinchoChar123tipoChar125SjcIndexRoute:
      GuinchoChar123tipoChar125SjcIndexRoute,
  }

const GuinchoChar123tipoChar125SjcRouteWithChildren =
  GuinchoChar123tipoChar125SjcRoute._addFileChildren(
    GuinchoChar123tipoChar125SjcRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnuncieRoute: AnuncieRoute,
  AreasAtendidasRoute: AreasAtendidasRoute,
  AutoSocorroRoute: AutoSocorroRoute,
  BlogRoute: BlogRouteWithChildren,
  CoberturaRoute: CoberturaRoute,
  ContatoRoute: ContatoRoute,
  FrotaGuinchoRoute: FrotaGuinchoRoute,
  GuinchoDeMotosRoute: GuinchoDeMotosRoute,
  GuinchoEmChar123slugChar125Route: GuinchoEmChar123slugChar125Route,
  GuinchoLeveRoute: GuinchoLeveRoute,
  GuinchoPesadoRoute: GuinchoPesadoRoute,
  GuinchoPostosDutraSaoJoseDosCamposRoute:
    GuinchoPostosDutraSaoJoseDosCamposRoute,
  GuinchoChar123tipoChar125SjcRoute:
    GuinchoChar123tipoChar125SjcRouteWithChildren,
  GuinchosNasRodoviasChar123slugChar125Route:
    GuinchosNasRodoviasChar123slugChar125Route,
  PaneSecaRoute: PaneSecaRoute,
  RemocaoVeicularRoute: RemocaoVeicularRoute,
  RodoviasValeDoParaibaRoute: RodoviasValeDoParaibaRoute,
  ServicosRoute: ServicosRoute,
  ServicosDeGuinchoEReboqueRoute: ServicosDeGuinchoEReboqueRoute,
  GuinchoSjcBairroRoute: GuinchoSjcBairroRoute,
  GuinchoSjcIndexRoute: GuinchoSjcIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
