/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosDeGuinchoEReboqueRouteImport } from './routes/servicos-de-guincho-e-reboque'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RodoviasValeDoParaibaRouteImport } from './routes/rodovias-vale-do-paraiba'
import { Route as RemocaoVeicularRouteImport } from './routes/remocao-veicular'
import { Route as PaneSecaRouteImport } from './routes/pane-seca'
import { Route as GuinchoPesadoRouteImport } from './routes/guincho-pesado'
import { Route as GuinchoLeveRouteImport } from './routes/guincho-leve'
import { Route as GuinchoEmChar123slugChar125RouteImport } from './routes/guincho-em-{$slug}'
import { Route as GuinchoDeMotosRouteImport } from './routes/guincho-de-motos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AutoSocorroRouteImport } from './routes/auto-socorro'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ServicosDeGuinchoEReboqueRoute =
  ServicosDeGuinchoEReboqueRouteImport.update({
    id: '/servicos-de-guincho-e-reboque',
    path: '/servicos-de-guincho-e-reboque',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RodoviasValeDoParaibaRoute = RodoviasValeDoParaibaRouteImport.update({
  id: '/rodovias-vale-do-paraiba',
  path: '/rodovias-vale-do-paraiba',
  getParentRoute: () => rootRouteImport,
} as any)
const RemocaoVeicularRoute = RemocaoVeicularRouteImport.update({
  id: '/remocao-veicular',
  path: '/remocao-veicular',
  getParentRoute: () => rootRouteImport,
} as any)
const PaneSecaRoute = PaneSecaRouteImport.update({
  id: '/pane-seca',
  path: '/pane-seca',
  getParentRoute: () => rootRouteImport,
} as any)
const GuinchoPesadoRoute = GuinchoPesadoRouteImport.update({
  id: '/guincho-pesado',
  path: '/guincho-pesado',
  getParentRoute: () => rootRouteImport,
} as any)
const GuinchoLeveRoute = GuinchoLeveRouteImport.update({
  id: '/guincho-leve',
  path: '/guincho-leve',
  getParentRoute: () => rootRouteImport,
} as any)
const GuinchoEmChar123slugChar125Route =
  GuinchoEmChar123slugChar125RouteImport.update({
    id: '/guincho-em-{$slug}',
    path: '/guincho-em-{$slug}',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuinchoDeMotosRoute = GuinchoDeMotosRouteImport.update({
  id: '/guincho-de-motos',
  path: '/guincho-de-motos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoSocorroRoute = AutoSocorroRouteImport.update({
  id: '/auto-socorro',
  path: '/auto-socorro',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/auto-socorro': typeof AutoSocorroRoute
  '/blog': typeof BlogRouteWithChildren
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/guincho-de-motos': typeof GuinchoDeMotosRoute
  '/guincho-em-{$slug}': typeof GuinchoEmChar123slugChar125Route
  '/guincho-leve': typeof GuinchoLeveRoute
  '/guincho-pesado': typeof GuinchoPesadoRoute
  '/pane-seca': typeof PaneSecaRoute
  '/remocao-veicular': typeof RemocaoVeicularRoute
  '/rodovias-vale-do-paraiba': typeof RodoviasValeDoParaibaRoute
  '/servicos': typeof ServicosRoute
  '/servicos-de-guincho-e-reboque': typeof ServicosDeGuinchoEReboqueRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/auto-socorro': typeof AutoSocorroRoute
  '/blog': typeof BlogRouteWithChildren
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/guincho-de-motos': typeof GuinchoDeMotosRoute
  '/guincho-em-{$slug}': typeof GuinchoEmChar123slugChar125Route
  '/guincho-leve': typeof GuinchoLeveRoute
  '/guincho-pesado': typeof GuinchoPesadoRoute
  '/pane-seca': typeof PaneSecaRoute
  '/remocao-veicular': typeof RemocaoVeicularRoute
  '/rodovias-vale-do-paraiba': typeof RodoviasValeDoParaibaRoute
  '/servicos': typeof ServicosRoute
  '/servicos-de-guincho-e-reboque': typeof ServicosDeGuinchoEReboqueRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/auto-socorro': typeof AutoSocorroRoute
  '/blog': typeof BlogRouteWithChildren
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/guincho-de-motos': typeof GuinchoDeMotosRoute
  '/guincho-em-{$slug}': typeof GuinchoEmChar123slugChar125Route
  '/guincho-leve': typeof GuinchoLeveRoute
  '/guincho-pesado': typeof GuinchoPesadoRoute
  '/pane-seca': typeof PaneSecaRoute
  '/remocao-veicular': typeof RemocaoVeicularRoute
  '/rodovias-vale-do-paraiba': typeof RodoviasValeDoParaibaRoute
  '/servicos': typeof ServicosRoute
  '/servicos-de-guincho-e-reboque': typeof ServicosDeGuinchoEReboqueRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anuncie'
    | '/auto-socorro'
    | '/blog'
    | '/cobertura'
    | '/contato'
    | '/guincho-de-motos'
    | '/guincho-em-{$slug}'
    | '/guincho-leve'
    | '/guincho-pesado'
    | '/pane-seca'
    | '/remocao-veicular'
    | '/rodovias-vale-do-paraiba'
    | '/servicos'
    | '/servicos-de-guincho-e-reboque'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anuncie'
    | '/auto-socorro'
    | '/blog'
    | '/cobertura'
    | '/contato'
    | '/guincho-de-motos'
    | '/guincho-em-{$slug}'
    | '/guincho-leve'
    | '/guincho-pesado'
    | '/pane-seca'
    | '/remocao-veicular'
    | '/rodovias-vale-do-paraiba'
    | '/servicos'
    | '/servicos-de-guincho-e-reboque'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anuncie'
    | '/auto-socorro'
    | '/blog'
    | '/cobertura'
    | '/contato'
    | '/guincho-de-motos'
    | '/guincho-em-{$slug}'
    | '/guincho-leve'
    | '/guincho-pesado'
    | '/pane-seca'
    | '/remocao-veicular'
    | '/rodovias-vale-do-paraiba'
    | '/servicos'
    | '/servicos-de-guincho-e-reboque'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnuncieRoute: typeof AnuncieRoute
  AutoSocorroRoute: typeof AutoSocorroRoute
  BlogRoute: typeof BlogRouteWithChildren
  CoberturaRoute: typeof CoberturaRoute
  ContatoRoute: typeof ContatoRoute
  GuinchoDeMotosRoute: typeof GuinchoDeMotosRoute
  GuinchoEmChar123slugChar125Route: typeof GuinchoEmChar123slugChar125Route
  GuinchoLeveRoute: typeof GuinchoLeveRoute
  GuinchoPesadoRoute: typeof GuinchoPesadoRoute
  PaneSecaRoute: typeof PaneSecaRoute
  RemocaoVeicularRoute: typeof RemocaoVeicularRoute
  RodoviasValeDoParaibaRoute: typeof RodoviasValeDoParaibaRoute
  ServicosRoute: typeof ServicosRoute
  ServicosDeGuinchoEReboqueRoute: typeof ServicosDeGuinchoEReboqueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos-de-guincho-e-reboque': {
      id: '/servicos-de-guincho-e-reboque'
      path: '/servicos-de-guincho-e-reboque'
      fullPath: '/servicos-de-guincho-e-reboque'
      preLoaderRoute: typeof ServicosDeGuinchoEReboqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rodovias-vale-do-paraiba': {
      id: '/rodovias-vale-do-paraiba'
      path: '/rodovias-vale-do-paraiba'
      fullPath: '/rodovias-vale-do-paraiba'
      preLoaderRoute: typeof RodoviasValeDoParaibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remocao-veicular': {
      id: '/remocao-veicular'
      path: '/remocao-veicular'
      fullPath: '/remocao-veicular'
      preLoaderRoute: typeof RemocaoVeicularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pane-seca': {
      id: '/pane-seca'
      path: '/pane-seca'
      fullPath: '/pane-seca'
      preLoaderRoute: typeof PaneSecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-pesado': {
      id: '/guincho-pesado'
      path: '/guincho-pesado'
      fullPath: '/guincho-pesado'
      preLoaderRoute: typeof GuinchoPesadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-leve': {
      id: '/guincho-leve'
      path: '/guincho-leve'
      fullPath: '/guincho-leve'
      preLoaderRoute: typeof GuinchoLeveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-em-{$slug}': {
      id: '/guincho-em-{$slug}'
      path: '/guincho-em-{$slug}'
      fullPath: '/guincho-em-{$slug}'
      preLoaderRoute: typeof GuinchoEmChar123slugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-de-motos': {
      id: '/guincho-de-motos'
      path: '/guincho-de-motos'
      fullPath: '/guincho-de-motos'
      preLoaderRoute: typeof GuinchoDeMotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-socorro': {
      id: '/auto-socorro'
      path: '/auto-socorro'
      fullPath: '/auto-socorro'
      preLoaderRoute: typeof AutoSocorroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnuncieRoute: AnuncieRoute,
  AutoSocorroRoute: AutoSocorroRoute,
  BlogRoute: BlogRouteWithChildren,
  CoberturaRoute: CoberturaRoute,
  ContatoRoute: ContatoRoute,
  GuinchoDeMotosRoute: GuinchoDeMotosRoute,
  GuinchoEmChar123slugChar125Route: GuinchoEmChar123slugChar125Route,
  GuinchoLeveRoute: GuinchoLeveRoute,
  GuinchoPesadoRoute: GuinchoPesadoRoute,
  PaneSecaRoute: PaneSecaRoute,
  RemocaoVeicularRoute: RemocaoVeicularRoute,
  RodoviasValeDoParaibaRoute: RodoviasValeDoParaibaRoute,
  ServicosRoute: ServicosRoute,
  ServicosDeGuinchoEReboqueRoute: ServicosDeGuinchoEReboqueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
